### ISSUE TITLE
As rotas não estão protegidas no router. 

### ISSUE THREAD

**Issue by brunomateus** [LViniciusk/achadex-vue#2]
https://github.com/LViniciusk/achadex-vue/blob/e53b2bedbc3712c65f76ee9a71621a6e0b7ec60c/src/router/index.js#L4

https://github.com/LViniciusk/achadex-vue/blob/e53b2bedbc3712c65f76ee9a71621a6e0b7ec60c/src/views/AddItem.vue#L118

Da forma que foi implementada a proteção da rotas o  código não reusável. Além disso, poderia gerar bastante código duplicado.

**Comment by LViniciusk** [comment]
Todas as rotas devidamente protegidas
