### ISSUE TITLE
O formulário de adicionar item não está validando os dados.

### ISSUE THREAD

**Issue by brunomateus** [LViniciusk/achadex-vue#3]
Se o usuário não informar nada, da erro 400 por conta do formato da data e nenhum feedback é passado para o usuário.
Se o usuário informar somente a data, um item sem nome, sem foto é cadastrado com sucesso.

**Comment by brunomateus** [comment]
<img width="909" alt="Captura de Tela 2024-09-18 às 19 02 25" src="https://github.com/user-attachments/assets/5bb74f2e-a24a-47fd-b2b8-e4a95fab6e01">

**Comment by LViniciusk** [comment]
Formulário devidamente validado
