### ISSUE TITLE
Computed properties seria o ideal

### ISSUE THREAD

**Issue by brunomateus** [LViniciusk/achadex-vue#4]
https://github.com/LViniciusk/achadex-vue/blob/e53b2bedbc3712c65f76ee9a71621a6e0b7ec60c/src/views/Home.vue#L18

Ao invés de usar o v-show desta forma, bastaria você ter uma computed properties que seria os itens que deveriam ser visualizados.

https://vuejs.org/guide/essentials/computed.html#computed-caching-vs-methods

**Comment by LViniciusk** [comment]
Implementação do Computed feita
