### ISSUE TITLE
Má prática 

### ISSUE THREAD

**Issue by brunomateus** [LViniciusk/achadex-vue#7]
Usar querySelector é má prática quando se trabalha com Vue/React ou afins. 
O correto seria usar o binding no atributo clicked, não precisaria do index.
Ex:   `:clicked`

https://github.com/LViniciusk/achadex-vue/blob/e53b2bedbc3712c65f76ee9a71621a6e0b7ec60c/src/views/Home.vue#L155

**Comment by brunomateus** [comment]
https://github.com/LViniciusk/achadex-vue/blob/e53b2bedbc3712c65f76ee9a71621a6e0b7ec60c/src/views/Login.vue#L112

Mesma coisa aqui

**Comment by LViniciusk** [comment]
Devidamente corrigido
